USE master
IF DB_ID (N'JournalForSchool') IS NOT NULL 
BEGIN
  ALTER DATABASE JournalForSchool SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE JournalForSchool;
END;
GO

CREATE DATABASE JournalForSchool;
GO
USE JournalForSchool;
GO


CREATE TABLE TheClasses(
    Id INT IDENTITY(1, 1) NOT NULL,
    TheClass INT NOT NULL,
    ClassLetter NCHAR(1) NOT NULL,
    PRIMARY KEY CLUSTERED(Id ASC)
);

CREATE TABLE Subjects(
    Id INT IDENTITY(1, 1) NOT NULL,
    SubjectName NVARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT PK_Subjects PRIMARY KEY CLUSTERED(Id ASC)
);



CREATE TABLE Users(
    Id INT IDENTITY(1, 1) NOT NULL,
    FirstName NVARCHAR(30) NOT NULL,
    MiddleName NVARCHAR(30) NOT NULL,
    LastName NVARCHAR(30) NOT NULL,
    TheClassesId INT NULL,
    Login NVARCHAR(30) UNIQUE NOT NULL,
    Password NVARCHAR(30) NOT NULL,
    Phone NVARCHAR(30) DEFAULT('0') NOT NULL,
    ImagePath VARCHAR(255) NULL,

    FOREIGN KEY(TheClassesId) REFERENCES TheClasses(Id) ON DELETE SET NULL,
    CONSTRAINT PK_Users PRIMARY KEY CLUSTERED(Id ASC)
)


CREATE TABLE Teachers(
    Id INT IDENTITY(1, 1) NOT NULL,
    UserId INT NOT NULL,
    SubjectId INT NULL,
    TheClassMentorId INT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    
    FOREIGN KEY(SubjectId) REFERENCES Subjects(Id) ON DELETE SET NULL,
    CONSTRAINT PK_Teachers PRIMARY KEY CLUSTERED(Id ASC)
);


CREATE TABLE Admins(
    Id INT IDENTITY(1, 1) NOT NULL,
    UserId INT NULL UNIQUE,
    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE SET NULL,
    CONSTRAINT PK_Admins PRIMARY KEY CLUSTERED(Id ASC)
);


CREATE TABLE Timetables(
    Id INT IDENTITY(1, 1) NOT NULL,
    LessonNumber INT NOT NULL,
    SubjectId INT NOT NULL,
    ClassId INT NOT NULL,
    TeacherID INT DEFAULT(1) NOT NULL,
    Monday BIT DEFAULT(0) NOT NULL,
    Tuesday BIT DEFAULT(0) NOT NULL,
    Wednesday BIT DEFAULT(0) NOT NULL, 
    Thursday BIT DEFAULT(0) NOT NULL,
    Friday  BIT DEFAULT(0) NOT NULL,
    FOREIGN KEY(SubjectId) REFERENCES Subjects(Id) ON DELETE CASCADE,
    FOREIGN KEY(ClassId) REFERENCES TheClasses(Id) ON DELETE CASCADE,
    FOREIGN KEY(TeacherId) REFERENCES Teachers(Id) ON DELETE CASCADE,

    CONSTRAINT PK_Timetable PRIMARY KEY CLUSTERED(Id ASC)
);


CREATE TABLE Marks(
    Id INT IDENTITY(1, 1) NOT NULL,
    UserId INT NOT NULL,
    TimeTableId INT NOT NULL,
    SelectedIndex INT NULL,
    Date VARCHAR(20) NOT NULL,
    FOREIGN KEY(TimeTableId) REFERENCES Timetables(Id) ON DELETE CASCADE,
    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE NO ACTION,
    CONSTRAINT PK_Marks PRIMARY KEY CLUSTERED(Id ASC)
);